### ISSUE TITLE
Spec the host and runtime behavoir `im-online` regarding module

### ISSUE THREAD

**Issue by drskalman** [w3f/polkadot-spec#330] opened 2020-12-09 17:07 UTC
The points which are still needed to clarify is:
 - Who (runtime/host) is going to (or can) make sure that the gossiped im-online transaction is actually was included in the best/finalized chain.
 - How does host/runtime figures out that other validator has not been online and issue slash for them.

**Comment by lamafab** [comment] 2020-12-16 16:55
Fixed in #333

**Comment by lamafab** [comment] 2021-01-19 13:02
This section will probably be removed entirely (see Pierre's review in #333). As long as the Host API works as intended, this part is fully managed by the Runtime.

**Closed as completed by lamafab** 2021-01-19 13:02 UTC
Labels: specification
