### ISSUE TITLE
Expand the SCALE test to cover all types which have SCALE encoding

### ISSUE THREAD

**Issue by drskalman** [w3f/polkadot-spec#118] opened 2020-01-28 20:25 UTC
Specifically Kagome team reported some bug in their SCALE implementation, it would be good if our tests can catch those
   problem.

**Comment by FlorianFranzen** [comment] 2021-01-15 16:42
Duplicate of #38?

**Comment by lamafab** [comment] 2021-01-27 17:07
Closing on behalf of #38

**Closed as completed by lamafab** 2021-01-27 17:07 UTC
